-- users 테이블에 레벨 정보 + 추가 인증 컬럼
ALTER TABLE users ADD COLUMN IF NOT EXISTS tamer_lv INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS digi_lv INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS upper_dungeon_verified BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS upper_field_verified BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS driver_verified BOOLEAN NOT NULL DEFAULT false;
